# Generated by Django 4.1.3 on 2022-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaignid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subcatname', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=500)),
                ('ldate', models.CharField(max_length=10)),
                ('edate', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
