# Generated by Django 4.1.3 on 2022-12-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_campaigns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='discription',
            new_name='description',
        ),
    ]
